#!/bin/zsh
# -*- sh-mode -*-

# o for open

jpgapp=geeqie
pngapp=geeqie
gifapp=geeqie

pdfapp=okular
debug=

if [[ $1 == "--debug" ]]
then
    echo entering debug mode ...
    echo showing instead of executing commands ...
    shift
    debug=echo
fi

for i in $*
do
    case $i:e in
        jpg|jpeg|JPG)
            $debug $jpgapp $i
            ;;
        
        png|PNG)
            $debug $pngapp $i
            ;;
        
        gif|GIF)
            $debug $pngapp $i
            ;;
        
        pdf|PDF)
            $debug $pdfapp $i
            ;;
        
        *)
            $debug emacsclient --no-wait $i
            ;;
    esac
done
