#!/bin/zsh
# -*- sh-mode -*-

# o for open

for i in $*
do
    ext=`echo $i | sed -e 's/.*\.//'`
    echo "ext: $ext"
    case "$ext" in
	jpg|JPG) geeqie $i ;;
	*)       emacsclient --no-wait $i & ;;
    esac
done
