#!/bin/zsh
# -*- sh-mode -*-

# o for open

for i in $*
do
    ext=`echo $i | sed -e 's/.*\.//'`
    case "$ext" in
	jpg|JPG) geeqie $i & ;;
	pdf|PDF) okular $i & ;;
	*)       emacsclient --no-wait $i & ;;
    esac
done
